version: '3.8'
services:  
   keycloak:
    image: jboss/keycloak:15.0.2
    environment:      
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: h2

    ports:  
      - "0.0.0.0:8080:8080"
